import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, test } from 'vitest'
import { readEvidenceMap } from './evidence.js'
import { GLOSSARY_MARKER, generateGlossaryPage, readGlossary, renderGlossary } from './glossary.js'
import { listRequests } from './history.js'
import { loadProject, saveProjectSettings, scaffoldProject } from './project.js'
import { validateProject } from './validation.js'

const roots: string[] = []

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })))
})

async function scaffold(terminology: Record<string, string>): Promise<string> {
  const parent = await mkdtemp(join(tmpdir(), 'doxloop-glossary-'))
  roots.push(parent)
  const root = await scaffoldProject({ directory: join(parent, 'docs'), title: 'Pulse', sources: [], generator: 'doxbrix' })
  const project = await loadProject(root)
  await saveProjectSettings(root, { documentation: { ...project.documentation, terminology } })
  return root
}

describe('glossary page', () => {
  test('merges brief and plan terminology, newest brief entry winning', async () => {
    const root = await scaffold({ Workspace: 'A shared container for projects.', Event: 'A single recorded occurrence.' })
    await writeFile(join(root, '.doxloop', 'documentation-plan.json'), JSON.stringify({ terminology: { Event: 'Ignored duplicate', Sink: 'A destination for events.' }, pages: [] }), 'utf8')
    const glossary = await readGlossary(root)
    expect(glossary.page).toBeUndefined()
    expect(glossary.generated).toBe(false)
    expect(glossary.fromPlan).toBe(1)
    expect(glossary.terms).toEqual([
      { term: 'Event', definition: 'A single recorded occurrence.' },
      { term: 'Sink', definition: 'A destination for events.' },
      { term: 'Workspace', definition: 'A shared container for projects.' },
    ])
  })

  test('writes the page, adds it to navigation, records evidence, and stays valid', async () => {
    const root = await scaffold({ Workspace: 'A shared container for projects, members, and billing.', Event: 'A single recorded occurrence sent to Pulse.' })
    const state = await generateGlossaryPage(root, {})
    expect(state.page).toBe('glossary.mdx')
    expect(state.generated).toBe(true)
    const page = await readFile(join(root, 'glossary.mdx'), 'utf8')
    expect(page).toContain(GLOSSARY_MARKER)
    expect(page).toContain('## Event\n\nA single recorded occurrence sent to Pulse.')
    expect(page.indexOf('## Event')).toBeLessThan(page.indexOf('## Workspace'))
    const config = JSON.parse(await readFile(join(root, 'docs.json'), 'utf8')) as { spaces: Array<{ nav: unknown[] }> }
    expect(JSON.stringify(config.spaces[0]!.nav)).toContain('"file":"glossary"')
    expect((await readEvidenceMap(root))?.pages['glossary.mdx']).toMatchObject({ sources: [], confidence: 'inferred' })
    const validation = await validateProject(root)
    expect(validation.issues.filter((issue) => issue.severity === 'error' && issue.file === 'glossary.mdx')).toEqual([])
    expect((await listRequests(root))[0]).toMatchObject({ kind: 'glossary', status: 'completed' })
    const again = await generateGlossaryPage(root, { terms: [{ term: 'Only', definition: 'One term.' }] })
    expect(again.generated).toBe(true)
    expect(await readFile(join(root, 'glossary.mdx'), 'utf8')).toContain('## Only')
  })

  test('refuses to overwrite a hand-written glossary unless asked, and needs at least one term', async () => {
    const root = await scaffold({})
    await expect(generateGlossaryPage(root, {})).rejects.toThrow('at least one term')
    await writeFile(join(root, 'glossary.mdx'), '---\ntitle: "Glossary"\ndescription: "Hand-written."\n---\n\n# Glossary\n\nMine.\n', 'utf8')
    const state = await readGlossary(root)
    expect(state.page).toBe('glossary.mdx')
    expect(state.generated).toBe(false)
    await expect(generateGlossaryPage(root, { terms: [{ term: 'A', definition: 'B' }] })).rejects.toThrow('not generated by Doxloop')
    const replaced = await generateGlossaryPage(root, { terms: [{ term: 'A', definition: 'B' }], replace: true })
    expect(replaced.generated).toBe(true)
  })

  test('renders reStructuredText and HTML glossaries for other generators', () => {
    const terms = [{ term: 'Zeta', definition: 'Last.' }, { term: 'Alpha', definition: 'First & foremost.' }]
    const rst = renderGlossary(terms, 'rst', 'Pulse')
    expect(rst).toContain('.. glossary::')
    expect(rst.indexOf('   Alpha')).toBeLessThan(rst.indexOf('   Zeta'))
    const html = renderGlossary(terms, 'html', 'Pulse')
    expect(html).toContain('<dt id="alpha">Alpha</dt>')
    expect(html).toContain('First &amp; foremost.')
    expect(html).toContain(GLOSSARY_MARKER)
  })
})
