import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { applyDirectEdit } from './direct-edit.js'
import { DoxloopError } from './errors.js'
import { EVIDENCE_MAP_FILE, readEvidenceMap, writeEvidenceMap } from './evidence.js'
import { pathExists, readJson, resolveContainedDirectory } from './fs.js'
import { loadGeneratorAdapter } from './generators.js'
import { appendDoxbrixNavigationPage } from './navigation.js'
import { loadProject, pageExtensions, relativePath, siteConfigPath } from './project.js'
import type { DoxloopProject, EvidenceMap } from './types.js'

/**
 * A glossary page generated from the documentation brief's terminology map,
 * so the terms a team curates in Settings become a reader-facing page without
 * an agent run. The page carries a marker so regenerating it never overwrites
 * a glossary a person wrote by hand.
 */
export const GLOSSARY_MARKER = 'doxloop:glossary'

export interface GlossaryTerm {
  term: string
  definition: string
}

export interface GlossaryState {
  /** Terms from the project brief, merged with the current plan's terminology. */
  terms: GlossaryTerm[]
  /** Project-relative path of the glossary page when one exists. */
  page?: string
  /** True when the existing page was generated by Doxloop and can be regenerated. */
  generated: boolean
  /** How many terms came from the current documentation plan rather than the brief. */
  fromPlan: number
}

export async function readGlossary(root: string): Promise<GlossaryState> {
  const project = await loadProject(root)
  const brief = termsFromRecord(project.documentation.terminology)
  const known = new Set(brief.map((entry) => entry.term.toLowerCase()))
  const planned = (await planTerminology(root)).filter((entry) => !known.has(entry.term.toLowerCase()))
  const location = await glossaryLocation(root, project)
  const exists = await pathExists(location.absolute)
  const generated = exists ? (await readFile(location.absolute, 'utf8')).includes(GLOSSARY_MARKER) : false
  return {
    terms: [...brief, ...planned].sort(byTerm),
    ...(exists ? { page: location.path } : {}),
    generated,
    fromPlan: planned.length,
  }
}

export async function generateGlossaryPage(root: string, raw: unknown): Promise<GlossaryState> {
  const body = raw && typeof raw === 'object' && !Array.isArray(raw) ? (raw as Record<string, unknown>) : {}
  const project = await loadProject(root)
  const state = await readGlossary(root)
  const terms = Array.isArray(body.terms) ? parseTerms(body.terms) : state.terms
  if (terms.length === 0) throw new DoxloopError('Add at least one term under Settings → Audience and voice before generating a glossary.', 2)
  const location = await glossaryLocation(root, project)
  if (state.page && !state.generated && body.replace !== true) {
    throw new DoxloopError(`${state.page} already exists and was not generated by Doxloop. Choose "Replace" to overwrite it.`)
  }
  const adapter = project.generator === 'doxbrix' ? undefined : await loadGeneratorAdapter(root, project)
  const content = renderGlossary(terms, location.format, project.title)
  const navigationFile = project.generator === 'doxbrix'
    ? relativePath(root, await siteConfigPath(root, project))
    : adapter?.planning?.navigationFiles[0]
  const files = [location.path, EVIDENCE_MAP_FILE, ...(navigationFile ? [navigationFile] : [])]
  await applyDirectEdit(root, {
    kind: 'glossary',
    requestText: `Generated the glossary from ${terms.length} term${terms.length === 1 ? '' : 's'}`,
    files,
    pagesChanged: 1,
    apply: async () => {
      await writeFile(location.absolute, content, 'utf8')
      if (project.generator === 'doxbrix') {
        await appendDoxbrixNavigationPage(root, project, { file: 'glossary', title: 'Glossary', icon: 'book', section: 'Reference' })
      } else if (adapter?.writeNavigation) {
        await adapter.writeNavigation({
          root,
          contentRoot: location.contentRoot,
          project,
          action: 'add',
          page: { path: location.contentRelative, title: 'Glossary', section: 'Reference' },
        })
      }
      const evidence: EvidenceMap = (await readEvidenceMap(root)) ?? { schemaVersion: 1, pages: {} }
      evidence.pages[location.path] = {
        sources: [],
        confidence: 'inferred',
        claims: terms.map((entry) => `${entry.term}: ${entry.definition}`),
      }
      await writeEvidenceMap(root, evidence)
    },
  })
  return readGlossary(root)
}

export function renderGlossary(terms: GlossaryTerm[], format: 'markdown' | 'rst' | 'html', productTitle: string): string {
  const sorted = [...terms].sort(byTerm)
  const description = `Definitions of the terms used across the ${productTitle} documentation.`
  if (format === 'rst') {
    const entries = sorted.map((entry) => `   ${entry.term}\n      ${entry.definition.replace(/\n+/g, ' ')}`).join('\n\n')
    return `.. ${GLOSSARY_MARKER}\n\nGlossary\n========\n\n${description}\n\n.. glossary::\n   :sorted:\n\n${entries}\n`
  }
  if (format === 'html') {
    const items = sorted.map((entry) => `      <dt id="${slug(entry.term)}">${escapeHtml(entry.term)}</dt>\n      <dd>${escapeHtml(entry.definition)}</dd>`).join('\n')
    return `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Glossary</title>\n    <meta name="description" content="${escapeHtml(description)}">\n    <!-- ${GLOSSARY_MARKER} -->\n  </head>\n  <body>\n    <main>\n      <h1>Glossary</h1>\n      <p>${escapeHtml(description)}</p>\n      <dl>\n${items}\n      </dl>\n    </main>\n  </body>\n</html>\n`
  }
  const sections = sorted.map((entry) => `## ${entry.term}\n\n${entry.definition.trim()}\n`).join('\n')
  return `---\ntitle: "Glossary"\ndescription: ${JSON.stringify(description)}\nicon: book\n---\n\n<!-- ${GLOSSARY_MARKER} -->\n\n# Glossary\n\n${description} Each entry gives the meaning Doxloop and the product use, so readers and writers share one vocabulary.\n\n${sections}`
}

async function glossaryLocation(root: string, project: DoxloopProject): Promise<{
  absolute: string
  path: string
  contentRelative: string
  contentRoot: string
  format: 'markdown' | 'rst' | 'html'
}> {
  const contentRoot = await resolveContainedDirectory(root, project.contentDir, 'Documentation content directory', {
    allowRoot: project.generator === 'doxbrix',
  })
  const adapter = project.generator === 'doxbrix' ? undefined : await loadGeneratorAdapter(root, project)
  const format = adapter?.project.contentFormat ?? 'markdown'
  const extensions = [...(await pageExtensions(root, project))]
  const extension = project.generator === 'doxbrix'
    ? '.mdx'
    : format === 'rst'
      ? '.rst'
      : format === 'html'
        ? '.html'
        : extensions.find((entry) => entry === '.md') ?? extensions[0] ?? '.md'
  const contentRelative = `glossary${extension}`
  const absolute = join(contentRoot, contentRelative)
  return { absolute, path: relativePath(root, absolute), contentRelative, contentRoot, format }
}

async function planTerminology(root: string): Promise<GlossaryTerm[]> {
  const path = join(root, '.doxloop', 'documentation-plan.json')
  if (!(await pathExists(path))) return []
  try {
    const plan = await readJson<{ terminology?: unknown }>(path)
    return termsFromRecord(plan.terminology)
  } catch {
    return []
  }
}

function termsFromRecord(value: unknown): GlossaryTerm[] {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return []
  return Object.entries(value as Record<string, unknown>)
    .filter((entry): entry is [string, string] => typeof entry[1] === 'string' && entry[0].trim() !== '' && entry[1].trim() !== '')
    .map(([term, definition]) => ({ term: term.trim(), definition: definition.trim() }))
}

function parseTerms(raw: unknown[]): GlossaryTerm[] {
  const seen = new Set<string>()
  const terms: GlossaryTerm[] = []
  for (const entry of raw) {
    const item = entry && typeof entry === 'object' ? (entry as Record<string, unknown>) : {}
    const term = typeof item.term === 'string' ? item.term.trim() : ''
    const definition = typeof item.definition === 'string' ? item.definition.trim() : ''
    if (!term || !definition) continue
    if (term.length > 80 || definition.length > 1000) throw new DoxloopError(`"${term.slice(0, 40)}" is too long for a glossary entry.`, 2)
    const key = term.toLowerCase()
    if (seen.has(key)) continue
    seen.add(key)
    terms.push({ term, definition })
  }
  return terms
}

function byTerm(left: GlossaryTerm, right: GlossaryTerm): number {
  return left.term.localeCompare(right.term, undefined, { sensitivity: 'base' })
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-+|-+$/g, '') || 'term'
}

function escapeHtml(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
}
